name: Run tests

on:
  workflow_call:
    inputs:
      runs-on:
        description: "Runner type"
        type: string
      git-version: 
        description: "Git version to use"
        type: string
      cache-key-prefix:
        description: "Prefix for cache key"
        type: string

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/test.yml
    with:
      name: Test
      asserted-cache-hit-status: false
      cache-key-prefix: ${{ inputs.cache-key-prefix }}
      runs-on: ${{ inputs.runs-on }}
      git-version: ${{ inputs.git-version }}
  cache-test:
    name: Run cache tests
    needs: test
    uses: ./.github/workflows/test.yml
    with:
      name: Cache test
      asserted-cache-hit-status: true
      cache-key-prefix: ${{ inputs.cache-key-prefix }}
      runs-on: ${{ inputs.runs-on }}
      git-version: ${{ inputs.git-version }}
